# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idx', models.SmallIntegerField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'managed': False,
                'db_table': 'chemicals',
            },
        ),
    ]
