# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idx', models.SmallIntegerField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'chemicals',
                'managed': False,
            },
        ),
    ]
