# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'abstracts',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('pmid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('year', models.SmallIntegerField()),
                ('title', models.TextField()),
                ('journal', models.CharField(max_length=256)),
                ('pub_date', models.CharField(max_length=256)),
                ('issue', models.CharField(blank=True, max_length=256, null=True)),
                ('pagination', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateField()),
                ('completed', models.DateField(blank=True, null=True)),
                ('revised', models.DateField(blank=True, null=True)),
                ('modified', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'citations',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('accession', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'databases',
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num', models.SmallIntegerField(blank=True, null=True)),
                ('major', models.BooleanField()),
                ('name', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'descriptors',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'managed': False,
                'db_table': 'identifiers',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.TextField(blank=True, null=True)),
                ('cnt', models.SmallIntegerField(blank=True, null=True)),
                ('major', models.BooleanField()),
                ('name', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'publication_types',
            },
        ),
    ]
