# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pos', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('initials', models.CharField(blank=True, max_length=128, null=True)),
                ('forename', models.CharField(blank=True, max_length=256, null=True)),
                ('suffix', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'authors',
            },
        ),
    ]
