# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifiers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num', models.SmallIntegerField(blank=True, null=True)),
                ('sub', models.SmallIntegerField(blank=True, null=True)),
                ('major', models.BooleanField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'qualifiers',
                'managed': False,
            },
        ),
    ]
